# Generated by Django 2.2.28 on 2022-10-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0134_profile_display_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_rank',
            field=models.CharField(choices=[('Administrador', 'Administrador del sitio'), ('Profesor', 'Acádemico del departamento'), ('Alumno', 'Alumno'), ('Visitante', 'Visitante')], default='Alumno', max_length=15, verbose_name='display rank'),
        ),
    ]
