# Generated by Django 2.2.28 on 2022-11-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0135_auto_20221005_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='JupyterWiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Wiki jupyter title')),
                ('content', models.TextField(verbose_name='Wiki jupyter content')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Language', verbose_name='language')),
            ],
            options={
                'verbose_name': 'jupyter wiki',
                'verbose_name_plural': 'jupyter wikis',
            },
        ),
        migrations.AddField(
            model_name='problemtype',
            name='wikis',
            field=models.ManyToManyField(help_text='Wiki in Jupyter notebooks for each language.', to='judge.JupyterWiki', verbose_name='language wikis'),
        ),
    ]
