# Generated by Django 2.2.28 on 2022-11-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0136_auto_20221109_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyterwiki',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='judge.Profile', verbose_name='author'),
        ),
    ]
