# Generated by Django 2.2.28 on 2022-11-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0137_jupyterwiki_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtype',
            name='wikis',
            field=models.ManyToManyField(help_text='Wiki in Jupyter notebooks for each language.', related_name='problemtype', to='judge.JupyterWiki', verbose_name='language wikis'),
        ),
    ]
