# Generated by Django 2.2.28 on 2022-11-10 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_auto_20221110_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='jupyterwiki',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='If wiki is public'),
        ),
        migrations.AddField(
            model_name='jupyterwiki',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='clarification timestamp'),
            preserve_default=False,
        ),
    ]
